import React from "react";
import { Composition } from "remotion";
import { Thumbnail } from "./Thumbnail";
import { thumbnailSchema } from "./schema/thumbnail";

/**
 * Three format compositions + template compositions, all sharing the Thumbnail
 * component and schema.
 *
 * IMPORTANT: `id` is a string literal and `defaultProps` is an INLINE object
 * literal (transforms written out in full, no spreads / imported variables).
 * This is required for Remotion Studio's "Save default props" feature — it
 * rewrites this file's defaultProps in place, and can only do so when the
 * values are statically extractable. See:
 * https://www.remotion.dev/docs/troubleshooting/cannot-save-default-props
 *
 * Sizes: Landscape 1280x720 (16:9), Portrait 1080x1920 (9:16), Square 1080x1080.
 */
export const RemotionRoot: React.FC = () => {
  return (
    <>
      {/* ---------- YouTube 16:9 ---------- */}
      <Composition
        id="Thumbnail-Landscape"
        component={Thumbnail}
        schema={thumbnailSchema}
        width={1280}
        height={720}
        fps={30}
        durationInFrames={1}
        defaultProps={{
          backgroundColor: "#0f172a",
          backgroundType: "solid",
          backgroundGradientFrom: "#1e293b",
          backgroundGradientTo: "#0f172a",
          backgroundGradientAngle: 135,
          backgroundImageSrc: "",
          backgroundImageFit: "cover",
          backgroundImageFocusX: 50,
          backgroundImageFocusY: 50,
          overlayType: "none",
          overlayColor: "#000000",
          overlayOpacity: 0.5,
          overlayZIndex: 50,
          noiseEnabled: false,
          noiseOpacity: 0.12,
          gridEnabled: false,
          gridSpacing: 100,
          gridColor: "#ffffff",
          gridOpacity: 0.35,
          shapes: [
            {
              kind: "rectangle",
              fillType: "linear",
              fillImageSrc: "",
              fillImageFit: "cover",
              fillImageFocusX: 50,
              fillImageFocusY: 50,
              fillColor: "#6366f1",
              gradientFrom: "#6366f1",
              gradientTo: "#0f172a",
              gradientAngle: 135,
              width: 1280,
              height: 720,
              borderRadius: 0,
              strokeColor: "#000000",
              strokeWidth: 0,
              backdropBlur: 0,
              shadowEnabled: false,
              shadowColor: "#000000",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 4,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 24,
              glowIntensity: 2,
              blur: 0,
              transform: { x: 0, y: 0, scale: 1, rotation: 0, opacity: 0.9, zIndex: 0 },
            },
            {
              kind: "rectangle",
              fillType: "solid",
              fillImageSrc: "",
              fillImageFit: "cover",
              fillImageFocusX: 50,
              fillImageFocusY: 50,
              fillColor: "#f59e0b",
              gradientFrom: "#f59e0b",
              gradientTo: "#000000",
              gradientAngle: 90,
              width: 380,
              height: 90,
              borderRadius: 12,
              strokeColor: "#000000",
              strokeWidth: 0,
              backdropBlur: 0,
              shadowEnabled: true,
              shadowColor: "#000000",
              shadowOpacity: 0.45,
              shadowAngle: 90,
              shadowDistance: 10,
              shadowBlur: 20,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 16,
              glowIntensity: 2,
              blur: 0,
              transform: { x: -360, y: 190, scale: 1, rotation: 0, opacity: 1, zIndex: 5 },
            },
          ],
          images: [],
          icons: [],
          qrcodes: [],
          lines: [],
          texts: [
            {
              text: "BUILD THIS\nIN 10 MINUTES",
              color: "#ffffff",
              fontFamily: "Anton",
              fontSize: 120,
              fontWeight: "900",
              align: "left",
              letterSpacing: 0,
              lineHeight: 0.95,
              maxWidth: 900,
              strokeColor: "#000000",
              strokeWidth: 6,
              backgroundColor: "#000000",
              backgroundEnabled: false,
              highlightColor: "#facc15",
              highlightTextColor: "#000000",
              highlightPaddingX: 10,
              highlightPaddingY: 2,
              highlightRadius: 6,
              curveRadius: 0,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 12,
              glowIntensity: 2,
              bgShadowEnabled: false,
              bgShadowColor: "#000000",
              bgShadowOpacity: 0.5,
              bgShadowAngle: 90,
              bgShadowDistance: 6,
              bgShadowBlur: 8,
              bgGlowEnabled: false,
              bgGlowColor: "#ffffff",
              bgGlowOpacity: 0.8,
              bgGlowSize: 16,
              bgGlowIntensity: 2,
              shadowEnabled: false,
              shadowColor: "#000000",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 4,
              paddingX: 20,
              paddingY: 8,
              borderRadius: 8,
              blur: 0,
              transform: { x: -230, y: -40, scale: 1, rotation: 0, opacity: 1, zIndex: 10 },
            },
            {
              text: "FULL TUTORIAL",
              color: "#0f172a",
              fontFamily: "Montserrat",
              fontSize: 40,
              fontWeight: "800",
              align: "center",
              letterSpacing: 2,
              lineHeight: 1,
              maxWidth: 0,
              strokeColor: "#000000",
              strokeWidth: 0,
              backgroundColor: "#f59e0b",
              backgroundEnabled: false,
              highlightColor: "#facc15",
              highlightTextColor: "#000000",
              highlightPaddingX: 10,
              highlightPaddingY: 2,
              highlightRadius: 6,
              curveRadius: 0,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 12,
              glowIntensity: 2,
              bgShadowEnabled: false,
              bgShadowColor: "#000000",
              bgShadowOpacity: 0.5,
              bgShadowAngle: 90,
              bgShadowDistance: 6,
              bgShadowBlur: 8,
              bgGlowEnabled: false,
              bgGlowColor: "#ffffff",
              bgGlowOpacity: 0.8,
              bgGlowSize: 16,
              bgGlowIntensity: 2,
              shadowEnabled: false,
              shadowColor: "#000000",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 4,
              paddingX: 20,
              paddingY: 8,
              borderRadius: 8,
              blur: 0,
              transform: { x: -360, y: 190, scale: 1, rotation: 0, opacity: 1, zIndex: 11 },
            },
          ],
        }}
      />

      {/* ---------- Reels / Stories 9:16 ---------- */}
      <Composition
        id="Thumbnail-Portrait"
        component={Thumbnail}
        schema={thumbnailSchema}
        width={1080}
        height={1920}
        fps={30}
        durationInFrames={1}
        defaultProps={{
          backgroundColor: "#111827",
          backgroundType: "solid",
          backgroundGradientFrom: "#1e293b",
          backgroundGradientTo: "#0f172a",
          backgroundGradientAngle: 135,
          backgroundImageSrc: "",
          backgroundImageFit: "cover",
          backgroundImageFocusX: 50,
          backgroundImageFocusY: 50,
          overlayType: "none",
          overlayColor: "#000000",
          overlayOpacity: 0.5,
          overlayZIndex: 50,
          noiseEnabled: false,
          noiseOpacity: 0.12,
          gridEnabled: false,
          gridSpacing: 100,
          gridColor: "#ffffff",
          gridOpacity: 0.35,
          shapes: [
            {
              kind: "rectangle",
              fillType: "linear",
              fillImageSrc: "",
              fillImageFit: "cover",
              fillImageFocusX: 50,
              fillImageFocusY: 50,
              fillColor: "#ec4899",
              gradientFrom: "#ec4899",
              gradientTo: "#111827",
              gradientAngle: 180,
              width: 1080,
              height: 1920,
              borderRadius: 0,
              strokeColor: "#000000",
              strokeWidth: 0,
              backdropBlur: 0,
              shadowEnabled: false,
              shadowColor: "#000000",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 4,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 24,
              glowIntensity: 2,
              blur: 0,
              transform: { x: 0, y: 0, scale: 1, rotation: 0, opacity: 0.85, zIndex: 0 },
            },
            {
              kind: "ellipse",
              fillType: "solid",
              fillImageSrc: "",
              fillImageFit: "cover",
              fillImageFocusX: 50,
              fillImageFocusY: 50,
              fillColor: "#22d3ee",
              gradientFrom: "#22d3ee",
              gradientTo: "#000000",
              gradientAngle: 90,
              width: 520,
              height: 520,
              borderRadius: 0,
              strokeColor: "#000000",
              strokeWidth: 0,
              backdropBlur: 0,
              shadowEnabled: false,
              shadowColor: "#000000",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 4,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 16,
              glowIntensity: 2,
              blur: 0,
              transform: { x: 0, y: -420, scale: 1, rotation: 0, opacity: 0.35, zIndex: 1 },
            },
          ],
          images: [],
          icons: [],
          qrcodes: [],
          lines: [],
          texts: [
            {
              text: "SWIPE\nUP",
              color: "#ffffff",
              fontFamily: "Anton",
              fontSize: 200,
              fontWeight: "900",
              align: "center",
              letterSpacing: 0,
              lineHeight: 0.9,
              maxWidth: 0,
              strokeColor: "#000000",
              strokeWidth: 8,
              backgroundColor: "#000000",
              backgroundEnabled: false,
              highlightColor: "#facc15",
              highlightTextColor: "#000000",
              highlightPaddingX: 10,
              highlightPaddingY: 2,
              highlightRadius: 6,
              curveRadius: 0,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 12,
              glowIntensity: 2,
              bgShadowEnabled: false,
              bgShadowColor: "#000000",
              bgShadowOpacity: 0.5,
              bgShadowAngle: 90,
              bgShadowDistance: 6,
              bgShadowBlur: 8,
              bgGlowEnabled: false,
              bgGlowColor: "#ffffff",
              bgGlowOpacity: 0.8,
              bgGlowSize: 16,
              bgGlowIntensity: 2,
              shadowEnabled: false,
              shadowColor: "#000000",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 4,
              paddingX: 20,
              paddingY: 8,
              borderRadius: 8,
              blur: 0,
              transform: { x: 0, y: -100, scale: 1, rotation: 0, opacity: 1, zIndex: 10 },
            },
            {
              text: "new drop today",
              color: "#111827",
              fontFamily: "Poppins",
              fontSize: 56,
              fontWeight: "700",
              align: "center",
              letterSpacing: 1,
              lineHeight: 1,
              maxWidth: 0,
              strokeColor: "#000000",
              strokeWidth: 0,
              backgroundColor: "#22d3ee",
              backgroundEnabled: true,
              highlightColor: "#facc15",
              highlightTextColor: "#000000",
              highlightPaddingX: 10,
              highlightPaddingY: 2,
              highlightRadius: 6,
              curveRadius: 0,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 12,
              glowIntensity: 2,
              bgShadowEnabled: false,
              bgShadowColor: "#000000",
              bgShadowOpacity: 0.5,
              bgShadowAngle: 90,
              bgShadowDistance: 6,
              bgShadowBlur: 8,
              bgGlowEnabled: false,
              bgGlowColor: "#ffffff",
              bgGlowOpacity: 0.8,
              bgGlowSize: 16,
              bgGlowIntensity: 2,
              shadowEnabled: false,
              shadowColor: "#000000",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 4,
              paddingX: 40,
              paddingY: 18,
              borderRadius: 999,
              blur: 0,
              transform: { x: 0, y: 260, scale: 1, rotation: 0, opacity: 1, zIndex: 11 },
            },
          ],
        }}
      />

      {/* ---------- Instagram Post 1:1 ---------- */}
      <Composition
        id="Thumbnail-Square"
        component={Thumbnail}
        schema={thumbnailSchema}
        width={1080}
        height={1080}
        fps={30}
        durationInFrames={1}
        defaultProps={{
          backgroundColor: "#fef3c7",
          backgroundType: "solid",
          backgroundGradientFrom: "#1e293b",
          backgroundGradientTo: "#0f172a",
          backgroundGradientAngle: 135,
          backgroundImageSrc: "",
          backgroundImageFit: "cover",
          backgroundImageFocusX: 50,
          backgroundImageFocusY: 50,
          overlayType: "none",
          overlayColor: "#000000",
          overlayOpacity: 0.5,
          overlayZIndex: 50,
          noiseEnabled: false,
          noiseOpacity: 0.12,
          gridEnabled: false,
          gridSpacing: 100,
          gridColor: "#ffffff",
          gridOpacity: 0.35,
          shapes: [
            {
              kind: "rectangle",
              fillType: "linear",
              fillImageSrc: "",
              fillImageFit: "cover",
              fillImageFocusX: 50,
              fillImageFocusY: 50,
              fillColor: "#fb7185",
              gradientFrom: "#fb7185",
              gradientTo: "#f59e0b",
              gradientAngle: 45,
              width: 1080,
              height: 1080,
              borderRadius: 0,
              strokeColor: "#000000",
              strokeWidth: 0,
              backdropBlur: 0,
              shadowEnabled: false,
              shadowColor: "#000000",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 4,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 24,
              glowIntensity: 2,
              blur: 0,
              transform: { x: 0, y: 0, scale: 1, rotation: 0, opacity: 1, zIndex: 0 },
            },
            {
              kind: "rectangle",
              fillType: "solid",
              fillImageSrc: "",
              fillImageFit: "cover",
              fillImageFocusX: 50,
              fillImageFocusY: 50,
              fillColor: "#ffffff",
              gradientFrom: "#ffffff",
              gradientTo: "#000000",
              gradientAngle: 90,
              width: 820,
              height: 820,
              borderRadius: 40,
              strokeColor: "#000000",
              strokeWidth: 0,
              backdropBlur: 0,
              shadowEnabled: false,
              shadowColor: "#000000",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 4,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 16,
              glowIntensity: 2,
              blur: 0,
              transform: { x: 0, y: 0, scale: 1, rotation: 0, opacity: 0.12, zIndex: 1 },
            },
          ],
          images: [],
          icons: [],
          qrcodes: [],
          lines: [],
          texts: [
            {
              text: "5 TIPS FOR\nBETTER PHOTOS",
              color: "#1f2937",
              fontFamily: "Montserrat",
              fontSize: 92,
              fontWeight: "900",
              align: "center",
              letterSpacing: 0,
              lineHeight: 1,
              maxWidth: 900,
              strokeColor: "#000000",
              strokeWidth: 0,
              backgroundColor: "#000000",
              backgroundEnabled: false,
              highlightColor: "#facc15",
              highlightTextColor: "#000000",
              highlightPaddingX: 10,
              highlightPaddingY: 2,
              highlightRadius: 6,
              curveRadius: 0,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 12,
              glowIntensity: 2,
              bgShadowEnabled: false,
              bgShadowColor: "#000000",
              bgShadowOpacity: 0.5,
              bgShadowAngle: 90,
              bgShadowDistance: 6,
              bgShadowBlur: 8,
              bgGlowEnabled: false,
              bgGlowColor: "#ffffff",
              bgGlowOpacity: 0.8,
              bgGlowSize: 16,
              bgGlowIntensity: 2,
              shadowEnabled: false,
              shadowColor: "#000000",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 4,
              paddingX: 20,
              paddingY: 8,
              borderRadius: 8,
              blur: 0,
              transform: { x: 0, y: -40, scale: 1, rotation: 0, opacity: 1, zIndex: 10 },
            },
            {
              text: "@yourhandle",
              color: "#ffffff",
              fontFamily: "Poppins",
              fontSize: 40,
              fontWeight: "600",
              align: "center",
              letterSpacing: 1,
              lineHeight: 1,
              maxWidth: 0,
              strokeColor: "#000000",
              strokeWidth: 0,
              backgroundColor: "#1f2937",
              backgroundEnabled: true,
              highlightColor: "#facc15",
              highlightTextColor: "#000000",
              highlightPaddingX: 10,
              highlightPaddingY: 2,
              highlightRadius: 6,
              curveRadius: 0,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 12,
              glowIntensity: 2,
              bgShadowEnabled: false,
              bgShadowColor: "#000000",
              bgShadowOpacity: 0.5,
              bgShadowAngle: 90,
              bgShadowDistance: 6,
              bgShadowBlur: 8,
              bgGlowEnabled: false,
              bgGlowColor: "#ffffff",
              bgGlowOpacity: 0.8,
              bgGlowSize: 16,
              bgGlowIntensity: 2,
              shadowEnabled: false,
              shadowColor: "#000000",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 4,
              paddingX: 32,
              paddingY: 14,
              borderRadius: 999,
              blur: 0,
              transform: { x: 0, y: 360, scale: 1, rotation: 0, opacity: 1, zIndex: 11 },
            },
          ],
        }}
      />

      {/* ---------- Template: Top 10 Diagonal (16:9) ----------
          Two-tone angled blue block (navy rect behind a blue gradient, both
          rotated -11 so only the diagonal edge shows), yellow eyebrow tag,
          stacked white title, tilted CTA badge, and a full-bleed image slot.
          Set the image layer's `src` to a file in public/ to add your photo. */}
      <Composition
        id="Thumbnail-Landscape-Top10"
        component={Thumbnail}
        schema={thumbnailSchema}
        width={1280}
        height={720}
        fps={30}
        durationInFrames={1}
        defaultProps={{"backgroundColor":"#c9ccd1","backgroundType":"solid" as const,"backgroundGradientFrom":"#1e293b","backgroundGradientTo":"#0f172a","backgroundGradientAngle":135,"backgroundImageSrc":"","backgroundImageFit":"cover" as const,"backgroundImageFocusX":50,"backgroundImageFocusY":50,"overlayType":"vignette" as const,"overlayColor":"#000000","overlayOpacity":0.5,"overlayZIndex":50,"noiseEnabled":false,"noiseOpacity":0.12,"gridEnabled":false,"gridSpacing":100,"gridColor":"#000000","gridOpacity":0.35,"icons":[{"iconName":"f7:chevron-right-2","color":"#ffffff","size":78,"fillType":"solid" as const,"gradientFrom":"#6366f1","gradientTo":"#a855f7","gradientAngle":135,"fillImageSrc":"","fillImageFit":"cover" as const,"fillImageFocusX":50,"fillImageFocusY":50,"outlineEnabled":false,"outlineColor":"#ffffff","outlineWidth":8,"shadowEnabled":false,"shadowColor":"#000000","shadowOpacity":0.5,"shadowAngle":90,"shadowDistance":6,"shadowBlur":4,"glowEnabled":false,"glowColor":"#ffffff","glowOpacity":0.8,"glowSize":16,"glowIntensity":2,"blur":0,"transform":{"x":-531,"y":-285,"scale":1,"rotation":0,"opacity":1,"zIndex":100}},{"iconName":"logos:spotify","color":"#ffffff","size":300,"fillType":"linear" as const,"gradientFrom":"#7d7d7d","gradientTo":"#ad96c4","gradientAngle":221,"fillImageSrc":"","fillImageFit":"cover" as const,"fillImageFocusX":50,"fillImageFocusY":50,"outlineEnabled":false,"outlineColor":"#ffffff","outlineWidth":8,"shadowEnabled":true,"shadowColor":"#000000","shadowOpacity":0.5,"shadowAngle":90,"shadowDistance":6,"shadowBlur":4,"glowEnabled":false,"glowColor":"#ffffff","glowOpacity":0.8,"glowSize":16,"glowIntensity":2,"blur":0,"transform":{"x":298,"y":199,"scale":1,"rotation":0,"opacity":1,"zIndex":100}}],"images":[{"src":"whiteboard.png","width":720,"height":720,"fit":"cover" as const,"borderRadius":0,"duotoneEnabled":false,"duotoneShadow":"#0f172a","duotoneHighlight":"#38bdf8","outlineEnabled":false,"outlineColor":"#ffffff","outlineWidth":8,"shadowEnabled":false,"shadowColor":"#000000","shadowOpacity":0.5,"shadowAngle":90,"shadowDistance":6,"shadowBlur":4,"glowEnabled":false,"glowColor":"#22d3ee","glowOpacity":0.8,"glowSize":24,"glowIntensity":2,"blur":0,"transform":{"x":303,"y":0,"scale":1,"rotation":0,"opacity":1,"zIndex":0}}],"shapes":[{"kind":"rectangle" as const,"fillType":"linear" as const,"fillImageSrc":"","fillImageFit":"cover" as const,"fillImageFocusX":50,"fillImageFocusY":50,"fillColor":"#3b82f6","gradientFrom":"#3b82f6","gradientTo":"#1e40af","gradientAngle":135,"width":1250,"height":1050,"borderRadius":0,"strokeColor":"#000000","strokeWidth":0,"backdropBlur":0,"shadowEnabled":false,"shadowColor":"#000000","shadowOpacity":0.5,"shadowAngle":90,"shadowDistance":6,"shadowBlur":4,"glowEnabled":false,"glowColor":"#ffffff","glowOpacity":0.8,"glowSize":24,"glowIntensity":2,"blur":0,"transform":{"x":-657,"y":0,"scale":1,"rotation":26,"opacity":1,"zIndex":3}},{"kind":"rectangle" as const,"fillType":"solid" as const,"fillImageSrc":"","fillImageFit":"cover" as const,"fillImageFocusX":50,"fillImageFocusY":50,"fillColor":"#1e3a8a","gradientFrom":"#1e3a8a","gradientTo":"#000000","gradientAngle":90,"width":1250,"height":1050,"borderRadius":0,"strokeColor":"#000000","strokeWidth":0,"backdropBlur":0,"shadowEnabled":false,"shadowColor":"#000000","shadowOpacity":0.5,"shadowAngle":90,"shadowDistance":6,"shadowBlur":4,"glowEnabled":false,"glowColor":"#ffffff","glowOpacity":0.8,"glowSize":16,"glowIntensity":2,"blur":0,"transform":{"x":-621,"y":0,"scale":1,"rotation":-11,"opacity":1,"zIndex":2}}],"qrcodes":[],"lines":[],"texts":[{"text":"TOP 10","color":"#000000","fontFamily":"Montserrat" as const,"fontSize":48,"fontWeight":"900" as const,"align":"center" as const,"letterSpacing":2,"lineHeight":1,"maxWidth":0,"strokeColor":"#000000","strokeWidth":0,"backgroundColor":"#facc15","backgroundEnabled":true,"highlightColor":"#facc15","highlightTextColor":"#000000","highlightPaddingX":10,"highlightPaddingY":2,"highlightRadius":6,"curveRadius":0,"glowEnabled":false,"glowColor":"#ffffff","glowOpacity":0.8,"glowSize":12,"glowIntensity":2,"bgShadowEnabled":true,"bgShadowColor":"#000000","bgShadowOpacity":0.5,"bgShadowAngle":45,"bgShadowDistance":16,"bgShadowBlur":8,"bgGlowEnabled":false,"bgGlowColor":"#ffffff","bgGlowOpacity":0.8,"bgGlowSize":16,"bgGlowIntensity":2,"shadowEnabled":true,"shadowColor":"#000000","shadowOpacity":0.44,"shadowAngle":45,"shadowDistance":6,"shadowBlur":4,"paddingX":26,"paddingY":10,"borderRadius":4,"blur":0,"transform":{"x":-443,"y":-195,"scale":1,"rotation":0,"opacity":1,"zIndex":10}},{"text":"PRODUCT\n==DIGITAL\nIDEAS==","color":"#ffffff","fontFamily":"Montserrat" as const,"fontSize":104,"fontWeight":"900" as const,"align":"left" as const,"letterSpacing":0,"lineHeight":1.15,"maxWidth":0,"strokeColor":"#000000","strokeWidth":0,"backgroundColor":"#000000","backgroundEnabled":false,"highlightColor":"#facc15","highlightTextColor":"#000000","highlightPaddingX":10,"highlightPaddingY":0,"highlightRadius":6,"curveRadius":0,"glowEnabled":false,"glowColor":"#ffffff","glowOpacity":0.8,"glowSize":12,"glowIntensity":2,"bgShadowEnabled":false,"bgShadowColor":"#000000","bgShadowOpacity":0.5,"bgShadowAngle":90,"bgShadowDistance":6,"bgShadowBlur":8,"bgGlowEnabled":false,"bgGlowColor":"#ffffff","bgGlowOpacity":0.8,"bgGlowSize":16,"bgGlowIntensity":2,"shadowEnabled":true,"shadowColor":"#000000","shadowOpacity":0.5,"shadowAngle":90,"shadowDistance":6,"shadowBlur":4,"paddingX":0,"paddingY":0,"borderRadius":0,"blur":0,"transform":{"x":-291,"y":21,"scale":1,"rotation":0,"opacity":1,"zIndex":10}},{"text":"WATCH ==NOW!==","color":"#ffffff","fontFamily":"Montserrat" as const,"fontSize":42,"fontWeight":"900" as const,"align":"center" as const,"letterSpacing":1,"lineHeight":1,"maxWidth":0,"strokeColor":"#000000","strokeWidth":0,"backgroundColor":"#1d4ed8","backgroundEnabled":true,"highlightColor":"#facc15","highlightTextColor":"#000000","highlightPaddingX":10,"highlightPaddingY":2,"highlightRadius":6,"curveRadius":0,"glowEnabled":false,"glowColor":"#ffffff","glowOpacity":0.8,"glowSize":12,"glowIntensity":2,"bgShadowEnabled":false,"bgShadowColor":"#000000","bgShadowOpacity":0.5,"bgShadowAngle":90,"bgShadowDistance":6,"bgShadowBlur":8,"bgGlowEnabled":false,"bgGlowColor":"#ffffff","bgGlowOpacity":0.8,"bgGlowSize":16,"bgGlowIntensity":2,"shadowEnabled":false,"shadowColor":"#000000","shadowOpacity":0.5,"shadowAngle":90,"shadowDistance":6,"shadowBlur":4,"paddingX":22,"paddingY":12,"borderRadius":2,"blur":0,"transform":{"x":304,"y":63,"scale":0.94,"rotation":-8,"opacity":1,"zIndex":12}},{"text":"... or die\ntrying","color":"#000000","fontFamily":"Permanent Marker" as const,"fontSize":65,"fontWeight":"700" as const,"align":"center" as const,"letterSpacing":0,"lineHeight":1,"maxWidth":0,"strokeColor":"#000000","strokeWidth":0,"backgroundColor":"#000000","backgroundEnabled":false,"paddingX":20,"paddingY":10,"borderRadius":8,"highlightColor":"#facc15","highlightTextColor":"#000000","highlightPaddingX":10,"highlightPaddingY":2,"highlightRadius":6,"curveRadius":0,"shadowEnabled":false,"shadowColor":"#000000","shadowOpacity":0.5,"shadowAngle":90,"shadowDistance":6,"shadowBlur":4,"glowEnabled":false,"glowColor":"#ffffff","glowOpacity":0.8,"glowSize":12,"glowIntensity":2,"bgShadowEnabled":false,"bgShadowColor":"#000000","bgShadowOpacity":0.5,"bgShadowAngle":90,"bgShadowDistance":6,"bgShadowBlur":8,"bgGlowEnabled":false,"bgGlowColor":"#ffffff","bgGlowOpacity":0.8,"bgGlowSize":16,"bgGlowIntensity":2,"blur":0,"transform":{"x":303,"y":170,"scale":1,"rotation":0,"opacity":0,"zIndex":100}}]}}
      />

      {/* ---------- Template: Modern Blue (16:9) ----------
          Geometric modern-tech look: full blue gradient, translucent triangle
          "arrow" accents, a full-height person image slot on the left, a stacked
          white headline (MODERN has a faint ghost copy behind it) and a white
          pill CTA. Set the image layer's `src` to a file in public/ for the photo.
          (Halftone dot patterns from the reference are omitted — no pattern
          primitive yet; add later as a PNG asset or a dedicated pattern layer.) */}
      <Composition
        id="Thumbnail-Landscape-ModernBlue"
        component={Thumbnail}
        schema={thumbnailSchema}
        width={1280}
        height={720}
        fps={30}
        durationInFrames={1}
        defaultProps={{
          backgroundColor: "#0a2a52",
          backgroundType: "solid",
          backgroundGradientFrom: "#1e293b",
          backgroundGradientTo: "#0f172a",
          backgroundGradientAngle: 135,
          backgroundImageSrc: "",
          backgroundImageFit: "cover",
          backgroundImageFocusX: 50,
          backgroundImageFocusY: 50,
          overlayType: "none",
          overlayColor: "#000000",
          overlayOpacity: 0.5,
          overlayZIndex: 50,
          noiseEnabled: false,
          noiseOpacity: 0.12,
          gridEnabled: false,
          gridSpacing: 100,
          gridColor: "#ffffff",
          gridOpacity: 0.35,
          shapes: [
            {
              kind: "rectangle",
              fillType: "linear",
              fillImageSrc: "",
              fillImageFit: "cover",
              fillImageFocusX: 50,
              fillImageFocusY: 50,
              fillColor: "#2b8fe0",
              gradientFrom: "#2b8fe0",
              gradientTo: "#0a2a52",
              gradientAngle: 120,
              width: 1280,
              height: 720,
              borderRadius: 0,
              strokeColor: "#000000",
              strokeWidth: 0,
              backdropBlur: 0,
              shadowEnabled: false,
              shadowColor: "#000000",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 4,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 24,
              glowIntensity: 2,
              blur: 0,
              transform: { x: 0, y: 0, scale: 1, rotation: 0, opacity: 1, zIndex: 0 },
            },
            {
              kind: "triangle",
              fillType: "solid",
              fillImageSrc: "",
              fillImageFit: "cover",
              fillImageFocusX: 50,
              fillImageFocusY: 50,
              gradientFrom: "#ffffff",
              gradientTo: "#000000",
              gradientAngle: 90,
              fillColor: "#3f9be8",
              width: 700,
              height: 700,
              borderRadius: 0,
              strokeColor: "#000000",
              strokeWidth: 0,
              backdropBlur: 0,
              shadowEnabled: false,
              shadowColor: "#000000",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 4,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 16,
              glowIntensity: 2,
              blur: 0,
              transform: { x: -170, y: -10, scale: 1, rotation: 0, opacity: 0.22, zIndex: 1 },
            },
            {
              kind: "triangle",
              fillType: "solid",
              fillImageSrc: "",
              fillImageFit: "cover",
              fillImageFocusX: 50,
              fillImageFocusY: 50,
              gradientFrom: "#ffffff",
              gradientTo: "#000000",
              gradientAngle: 90,
              fillColor: "#57a9ef",
              width: 340,
              height: 340,
              borderRadius: 0,
              strokeColor: "#000000",
              strokeWidth: 0,
              backdropBlur: 0,
              shadowEnabled: false,
              shadowColor: "#000000",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 4,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 16,
              glowIntensity: 2,
              blur: 0,
              transform: { x: 545, y: -250, scale: 1, rotation: 200, opacity: 0.28, zIndex: 1 },
            },
            {
              kind: "triangle",
              fillType: "solid",
              fillImageSrc: "",
              fillImageFit: "cover",
              fillImageFocusX: 50,
              fillImageFocusY: 50,
              gradientFrom: "#ffffff",
              gradientTo: "#000000",
              gradientAngle: 90,
              fillColor: "#1f6fc0",
              width: 380,
              height: 380,
              borderRadius: 0,
              strokeColor: "#000000",
              strokeWidth: 0,
              backdropBlur: 0,
              shadowEnabled: false,
              shadowColor: "#000000",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 4,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 16,
              glowIntensity: 2,
              blur: 0,
              transform: { x: 520, y: 275, scale: 1, rotation: 25, opacity: 0.3, zIndex: 1 },
            },
            {
              kind: "triangle",
              fillType: "solid",
              fillImageSrc: "",
              fillImageFit: "cover",
              fillImageFocusX: 50,
              fillImageFocusY: 50,
              gradientFrom: "#ffffff",
              gradientTo: "#000000",
              gradientAngle: 90,
              fillColor: "#57a9ef",
              width: 260,
              height: 260,
              borderRadius: 0,
              strokeColor: "#000000",
              strokeWidth: 0,
              backdropBlur: 0,
              shadowEnabled: false,
              shadowColor: "#000000",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 4,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 16,
              glowIntensity: 2,
              blur: 0,
              transform: { x: -560, y: 210, scale: 1, rotation: 180, opacity: 0.22, zIndex: 1 },
            },
          ],
          images: [
            {
              src: "",
              width: 620,
              height: 720,
              fit: "cover",
              borderRadius: 0,
              duotoneEnabled: false,
              duotoneShadow: "#0f172a",
              duotoneHighlight: "#38bdf8",
              outlineEnabled: false,
              outlineColor: "#ffffff",
              outlineWidth: 8,
              shadowEnabled: false,
              shadowColor: "#000000",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 4,
              glowEnabled: false,
              glowColor: "#22d3ee",
              glowOpacity: 0.8,
              glowSize: 24,
              glowIntensity: 2,
              blur: 0,
              transform: { x: -260, y: 0, scale: 1, rotation: 0, opacity: 1, zIndex: 5 },
            },
          ],
          icons: [],
          qrcodes: [],
          lines: [],
          texts: [
            {
              text: "MULTI PURPOSE",
              color: "#ffffff",
              fontFamily: "Montserrat",
              fontSize: 52,
              fontWeight: "900",
              align: "center",
              letterSpacing: 2,
              lineHeight: 1,
              maxWidth: 0,
              strokeColor: "#000000",
              strokeWidth: 0,
              backgroundColor: "#000000",
              backgroundEnabled: false,
              highlightColor: "#facc15",
              highlightTextColor: "#000000",
              highlightPaddingX: 10,
              highlightPaddingY: 2,
              highlightRadius: 6,
              curveRadius: 0,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 12,
              glowIntensity: 2,
              bgShadowEnabled: false,
              bgShadowColor: "#000000",
              bgShadowOpacity: 0.5,
              bgShadowAngle: 90,
              bgShadowDistance: 6,
              bgShadowBlur: 8,
              bgGlowEnabled: false,
              bgGlowColor: "#ffffff",
              bgGlowOpacity: 0.8,
              bgGlowSize: 16,
              bgGlowIntensity: 2,
              shadowEnabled: true,
              shadowColor: "#071a33",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 14,
              paddingX: 0,
              paddingY: 0,
              borderRadius: 0,
              blur: 0,
              transform: { x: 320, y: -200, scale: 1, rotation: 0, opacity: 1, zIndex: 10 },
            },
            {
              text: "MODERN",
              color: "#0b3566",
              fontFamily: "Montserrat",
              fontSize: 120,
              fontWeight: "900",
              align: "center",
              letterSpacing: 2,
              lineHeight: 1,
              maxWidth: 0,
              strokeColor: "#000000",
              strokeWidth: 0,
              backgroundColor: "#000000",
              backgroundEnabled: false,
              highlightColor: "#facc15",
              highlightTextColor: "#000000",
              highlightPaddingX: 10,
              highlightPaddingY: 2,
              highlightRadius: 6,
              curveRadius: 0,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 12,
              glowIntensity: 2,
              bgShadowEnabled: false,
              bgShadowColor: "#000000",
              bgShadowOpacity: 0.5,
              bgShadowAngle: 90,
              bgShadowDistance: 6,
              bgShadowBlur: 8,
              bgGlowEnabled: false,
              bgGlowColor: "#ffffff",
              bgGlowOpacity: 0.8,
              bgGlowSize: 16,
              bgGlowIntensity: 2,
              shadowEnabled: false,
              shadowColor: "#000000",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 4,
              paddingX: 0,
              paddingY: 0,
              borderRadius: 0,
              blur: 0,
              transform: { x: 328, y: -58, scale: 1, rotation: 0, opacity: 0.75, zIndex: 9 },
            },
            {
              text: "MODERN",
              color: "#ffffff",
              fontFamily: "Montserrat",
              fontSize: 120,
              fontWeight: "900",
              align: "center",
              letterSpacing: 2,
              lineHeight: 1,
              maxWidth: 0,
              strokeColor: "#000000",
              strokeWidth: 0,
              backgroundColor: "#000000",
              backgroundEnabled: false,
              highlightColor: "#facc15",
              highlightTextColor: "#000000",
              highlightPaddingX: 10,
              highlightPaddingY: 2,
              highlightRadius: 6,
              curveRadius: 0,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 12,
              glowIntensity: 2,
              bgShadowEnabled: false,
              bgShadowColor: "#000000",
              bgShadowOpacity: 0.5,
              bgShadowAngle: 90,
              bgShadowDistance: 6,
              bgShadowBlur: 8,
              bgGlowEnabled: false,
              bgGlowColor: "#ffffff",
              bgGlowOpacity: 0.8,
              bgGlowSize: 16,
              bgGlowIntensity: 2,
              shadowEnabled: true,
              shadowColor: "#071a33",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 8,
              shadowBlur: 18,
              paddingX: 0,
              paddingY: 0,
              borderRadius: 0,
              blur: 0,
              transform: { x: 315, y: -70, scale: 1, rotation: 0, opacity: 1, zIndex: 10 },
            },
            {
              text: "THUMBNAIL",
              color: "#ffffff",
              fontFamily: "Montserrat",
              fontSize: 90,
              fontWeight: "900",
              align: "center",
              letterSpacing: 2,
              lineHeight: 1,
              maxWidth: 0,
              strokeColor: "#000000",
              strokeWidth: 0,
              backgroundColor: "#000000",
              backgroundEnabled: false,
              highlightColor: "#facc15",
              highlightTextColor: "#000000",
              highlightPaddingX: 10,
              highlightPaddingY: 2,
              highlightRadius: 6,
              curveRadius: 0,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 12,
              glowIntensity: 2,
              bgShadowEnabled: false,
              bgShadowColor: "#000000",
              bgShadowOpacity: 0.5,
              bgShadowAngle: 90,
              bgShadowDistance: 6,
              bgShadowBlur: 8,
              bgGlowEnabled: false,
              bgGlowColor: "#ffffff",
              bgGlowOpacity: 0.8,
              bgGlowSize: 16,
              bgGlowIntensity: 2,
              shadowEnabled: true,
              shadowColor: "#071a33",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 8,
              shadowBlur: 18,
              paddingX: 0,
              paddingY: 0,
              borderRadius: 0,
              blur: 0,
              transform: { x: 315, y: 55, scale: 1, rotation: 0, opacity: 1, zIndex: 10 },
            },
            {
              text: "WATCH VIDEO NOW",
              color: "#0e3a6b",
              fontFamily: "Montserrat",
              fontSize: 34,
              fontWeight: "800",
              align: "center",
              letterSpacing: 2,
              lineHeight: 1,
              maxWidth: 0,
              strokeColor: "#000000",
              strokeWidth: 0,
              backgroundColor: "#ffffff",
              backgroundEnabled: true,
              highlightColor: "#facc15",
              highlightTextColor: "#000000",
              highlightPaddingX: 10,
              highlightPaddingY: 2,
              highlightRadius: 6,
              curveRadius: 0,
              glowEnabled: false,
              glowColor: "#ffffff",
              glowOpacity: 0.8,
              glowSize: 12,
              glowIntensity: 2,
              bgShadowEnabled: false,
              bgShadowColor: "#000000",
              bgShadowOpacity: 0.5,
              bgShadowAngle: 90,
              bgShadowDistance: 6,
              bgShadowBlur: 8,
              bgGlowEnabled: false,
              bgGlowColor: "#ffffff",
              bgGlowOpacity: 0.8,
              bgGlowSize: 16,
              bgGlowIntensity: 2,
              shadowEnabled: false,
              shadowColor: "#000000",
              shadowOpacity: 0.5,
              shadowAngle: 90,
              shadowDistance: 6,
              shadowBlur: 4,
              paddingX: 44,
              paddingY: 18,
              borderRadius: 999,
              blur: 0,
              transform: { x: 300, y: 175, scale: 1, rotation: 0, opacity: 1, zIndex: 11 },
            },
          ],
        }}
      />
    </>
  );
};
